        package com.undeadcrud.repository;

        import com.undeadcrud.domain.Undead;

        import java.sql.*;
        import java.util.ArrayList;
        import java.util.List;

public class UndeadRepositoryImpl implements UndeadRepository {

    private Connection connection;
    private PreparedStatement addUndeadsStatement;
    private PreparedStatement getAllStatement;
    private PreparedStatement getByIdStatement;
    private PreparedStatement deleteTableStatement;
    private PreparedStatement updateStatement;
    private PreparedStatement deleteByIdStatement;

    public UndeadRepositoryImpl(Connection connection) throws SQLException {

        this.connection = connection;
        if (!isReady()) {
            createTables();
        }
        setConnection(connection);
    }

    public UndeadRepositoryImpl() throws SQLException{

        this.connection = DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/workdb");
        if (!isReady()) {
            createTables();
        }
        this.setConnection(this.connection);


    }

//    public UndeadRepositoryImpl() throws SQLException
//    {}

    public Connection getConnection() {
        return connection;
    }

    /**
     * @param connection the connection to set
     */

    public void setConnection(Connection connection) throws SQLException {
        this.connection = connection;
        addUndeadsStatement = connection.prepareStatement("INSERT INTO Undeads (nazwa, typ, tier, lokacja, zdolnoscSpecjalna) VALUES (?, ?, ?, ?, ?)");
        getAllStatement = connection.prepareStatement("SELECT * FROM Undeads");
        getByIdStatement = connection.prepareStatement("SELECT * FROM Undeads WHERE ID = ?");
        updateStatement = connection.prepareStatement("UPDATE Undeads SET nazwa = ?, typ = ?, tier = ?, lokacja = ?, zdolnoscSpecjalna = 0, WHERE ID = ?");
        deleteTableStatement = connection.prepareStatement("DROP TABLE Undeads");
        deleteByIdStatement = connection.prepareStatement("DELETE FROM Undeads WHERE ID = ?");
    }


    public void createTables() throws SQLException {
        connection.createStatement().executeUpdate("CREATE TABLE Undeads " +
                "(id int GENERATED BY DEFAULT AS IDENTITY, " + " nazwa varchar(30) NOT NULL, " + " typ varchar(30), " + "tier INTEGER, " +
                 " lokacja varchar(30), " + " zdolnoscSpecjalna varchar(30)) ");
    }

    public boolean isReady() {
        try {
            ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
            boolean tableExists = false;
            while (rs.next()) {
                if ("Undeads".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
                    tableExists = true;
                    break;
                }
            }
            return tableExists;
        } catch (SQLException e) {
            return false;
        }
    }



    @Override
    public List<Undead> getAll() {
        List<Undead> undeads = new ArrayList<>();
        if(connection!=null){
            try {
                ResultSet rs = getAllStatement.executeQuery();

                while (rs.next()) {
                    Undead undead = new Undead();
                    undead.setId(rs.getInt("id"));
                    undead.setNazwa(rs.getString("nazwa"));
                    undead.setTyp(rs.getString("typ"));
                    undead.setTier(rs.getInt("tier"));
                    undead.setNazwa(rs.getString("lokacja"));
                    undead.setNazwa(rs.getString("zdolnoscSpecjalna"));
                    undeads.add(undead);
                }
            } catch (SQLException e) {
                throw new IllegalStateException(e.getMessage() + "\n" + e.getStackTrace().toString());
            }
            return undeads;
        }
        else return new ArrayList<>();
    }

    @Override
    public Undead getById(int id) {
        Undead undead = new Undead();

        try {
            getByIdStatement.setInt(1, id);
            ResultSet rs = getByIdStatement.executeQuery();

            while (rs.next()) {
                undead.setId(rs.getInt("id"));
                undead.setNazwa(rs.getString("nazwa"));
                undead.setTyp(rs.getString("typ"));
                undead.setTier(rs.getInt("tier"));
                undead.setNazwa(rs.getString("lokacja"));
                undead.setNazwa(rs.getString("zdolnoscSpecjalna"));
                return undead;
            }
        } catch (SQLException e) {
            throw new IllegalStateException(e.getMessage() + "\n" + e.getStackTrace().toString());
        }
        return undead;
    }



    @Override
    public int addUndead(Undead undead) {
        try {
            addUndeadsStatement.setString(1, undead.getNazwa());
            addUndeadsStatement.setString(2, undead.getTyp());
            addUndeadsStatement.setInt(3, undead.getTier());
            addUndeadsStatement.setString(4, undead.getLokacja());
            addUndeadsStatement.setString(5, undead.getZdolnoscSpecjalna());
            return addUndeadsStatement.executeUpdate();
        } catch (SQLException e) {
            throw new IllegalStateException(e.getMessage() + "\n" + e.getStackTrace().toString());
        }
    }


    @Override
    public int deleteUndead(Undead undead) throws SQLException {

        deleteByIdStatement.setInt(1, undead.getId());
        return deleteByIdStatement.executeUpdate();

    }

    @Override
    public int updateUndead(int Idbefore, Undead undead) throws SQLException {

        updateStatement.setString(1, undead.getNazwa());
        updateStatement.setString(2, undead.getTyp());
        updateStatement.setInt(3, undead.getTier());
        updateStatement.setString(4, undead.getLokacja());
        updateStatement.setString(5, undead.getZdolnoscSpecjalna());
        updateStatement.setInt(6, Idbefore);
        return updateStatement.executeUpdate();

    }

}
